/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CRouteImport } from './routes/c'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CIndexRouteImport } from './routes/c.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as CProfileRouteImport } from './routes/c.profile'
import { Route as CApplicationsRouteImport } from './routes/c.applications'
import { Route as AppRadarRouteImport } from './routes/app.radar'
import { Route as AppApplicantsRouteImport } from './routes/app.applicants'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppJobsIndexRouteImport } from './routes/app.jobs.index'
import { Route as CInterviewIdRouteImport } from './routes/c.interview.$id'
import { Route as CApplyIdRouteImport } from './routes/c.apply.$id'
import { Route as AppJobsNewRouteImport } from './routes/app.jobs.new'
import { Route as AppJobsIdRouteImport } from './routes/app.jobs.$id'

const CRoute = CRouteImport.update({
  id: '/c',
  path: '/c',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CIndexRoute = CIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const CProfileRoute = CProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CRoute,
} as any)
const CApplicationsRoute = CApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => CRoute,
} as any)
const AppRadarRoute = AppRadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicantsRoute = AppApplicantsRouteImport.update({
  id: '/applicants',
  path: '/applicants',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsIndexRoute = AppJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AppRoute,
} as any)
const CInterviewIdRoute = CInterviewIdRouteImport.update({
  id: '/interview/$id',
  path: '/interview/$id',
  getParentRoute: () => CRoute,
} as any)
const CApplyIdRoute = CApplyIdRouteImport.update({
  id: '/apply/$id',
  path: '/apply/$id',
  getParentRoute: () => CRoute,
} as any)
const AppJobsNewRoute = AppJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsIdRoute = AppJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/c': typeof CRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/applicants': typeof AppApplicantsRoute
  '/app/radar': typeof AppRadarRoute
  '/c/applications': typeof CApplicationsRoute
  '/c/profile': typeof CProfileRoute
  '/app/': typeof AppIndexRoute
  '/c/': typeof CIndexRoute
  '/app/jobs/$id': typeof AppJobsIdRoute
  '/app/jobs/new': typeof AppJobsNewRoute
  '/c/apply/$id': typeof CApplyIdRoute
  '/c/interview/$id': typeof CInterviewIdRoute
  '/app/jobs/': typeof AppJobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/applicants': typeof AppApplicantsRoute
  '/app/radar': typeof AppRadarRoute
  '/c/applications': typeof CApplicationsRoute
  '/c/profile': typeof CProfileRoute
  '/app': typeof AppIndexRoute
  '/c': typeof CIndexRoute
  '/app/jobs/$id': typeof AppJobsIdRoute
  '/app/jobs/new': typeof AppJobsNewRoute
  '/c/apply/$id': typeof CApplyIdRoute
  '/c/interview/$id': typeof CInterviewIdRoute
  '/app/jobs': typeof AppJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/c': typeof CRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/applicants': typeof AppApplicantsRoute
  '/app/radar': typeof AppRadarRoute
  '/c/applications': typeof CApplicationsRoute
  '/c/profile': typeof CProfileRoute
  '/app/': typeof AppIndexRoute
  '/c/': typeof CIndexRoute
  '/app/jobs/$id': typeof AppJobsIdRoute
  '/app/jobs/new': typeof AppJobsNewRoute
  '/c/apply/$id': typeof CApplyIdRoute
  '/c/interview/$id': typeof CInterviewIdRoute
  '/app/jobs/': typeof AppJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/c'
    | '/app/analytics'
    | '/app/applicants'
    | '/app/radar'
    | '/c/applications'
    | '/c/profile'
    | '/app/'
    | '/c/'
    | '/app/jobs/$id'
    | '/app/jobs/new'
    | '/c/apply/$id'
    | '/c/interview/$id'
    | '/app/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/analytics'
    | '/app/applicants'
    | '/app/radar'
    | '/c/applications'
    | '/c/profile'
    | '/app'
    | '/c'
    | '/app/jobs/$id'
    | '/app/jobs/new'
    | '/c/apply/$id'
    | '/c/interview/$id'
    | '/app/jobs'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/c'
    | '/app/analytics'
    | '/app/applicants'
    | '/app/radar'
    | '/c/applications'
    | '/c/profile'
    | '/app/'
    | '/c/'
    | '/app/jobs/$id'
    | '/app/jobs/new'
    | '/c/apply/$id'
    | '/c/interview/$id'
    | '/app/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CRoute: typeof CRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/c': {
      id: '/c'
      path: '/c'
      fullPath: '/c'
      preLoaderRoute: typeof CRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/': {
      id: '/c/'
      path: '/'
      fullPath: '/c/'
      preLoaderRoute: typeof CIndexRouteImport
      parentRoute: typeof CRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/c/profile': {
      id: '/c/profile'
      path: '/profile'
      fullPath: '/c/profile'
      preLoaderRoute: typeof CProfileRouteImport
      parentRoute: typeof CRoute
    }
    '/c/applications': {
      id: '/c/applications'
      path: '/applications'
      fullPath: '/c/applications'
      preLoaderRoute: typeof CApplicationsRouteImport
      parentRoute: typeof CRoute
    }
    '/app/radar': {
      id: '/app/radar'
      path: '/radar'
      fullPath: '/app/radar'
      preLoaderRoute: typeof AppRadarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/applicants': {
      id: '/app/applicants'
      path: '/applicants'
      fullPath: '/app/applicants'
      preLoaderRoute: typeof AppApplicantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jobs/': {
      id: '/app/jobs/'
      path: '/jobs'
      fullPath: '/app/jobs/'
      preLoaderRoute: typeof AppJobsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/c/interview/$id': {
      id: '/c/interview/$id'
      path: '/interview/$id'
      fullPath: '/c/interview/$id'
      preLoaderRoute: typeof CInterviewIdRouteImport
      parentRoute: typeof CRoute
    }
    '/c/apply/$id': {
      id: '/c/apply/$id'
      path: '/apply/$id'
      fullPath: '/c/apply/$id'
      preLoaderRoute: typeof CApplyIdRouteImport
      parentRoute: typeof CRoute
    }
    '/app/jobs/new': {
      id: '/app/jobs/new'
      path: '/jobs/new'
      fullPath: '/app/jobs/new'
      preLoaderRoute: typeof AppJobsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jobs/$id': {
      id: '/app/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/app/jobs/$id'
      preLoaderRoute: typeof AppJobsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApplicantsRoute: typeof AppApplicantsRoute
  AppRadarRoute: typeof AppRadarRoute
  AppIndexRoute: typeof AppIndexRoute
  AppJobsIdRoute: typeof AppJobsIdRoute
  AppJobsNewRoute: typeof AppJobsNewRoute
  AppJobsIndexRoute: typeof AppJobsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppApplicantsRoute: AppApplicantsRoute,
  AppRadarRoute: AppRadarRoute,
  AppIndexRoute: AppIndexRoute,
  AppJobsIdRoute: AppJobsIdRoute,
  AppJobsNewRoute: AppJobsNewRoute,
  AppJobsIndexRoute: AppJobsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CRouteChildren {
  CApplicationsRoute: typeof CApplicationsRoute
  CProfileRoute: typeof CProfileRoute
  CIndexRoute: typeof CIndexRoute
  CApplyIdRoute: typeof CApplyIdRoute
  CInterviewIdRoute: typeof CInterviewIdRoute
}

const CRouteChildren: CRouteChildren = {
  CApplicationsRoute: CApplicationsRoute,
  CProfileRoute: CProfileRoute,
  CIndexRoute: CIndexRoute,
  CApplyIdRoute: CApplyIdRoute,
  CInterviewIdRoute: CInterviewIdRoute,
}

const CRouteWithChildren = CRoute._addFileChildren(CRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CRoute: CRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
