"""
Direct Agent Test — No server, no HTTP, just Python.

Usage:
    python test_agent.py
    python test_agent.py --compact
    python test_agent.py --single "I worked on GraphRAG"
"""

import asyncio
# asyncio is needed because the agent uses async methods.
# We can't call `await` from regular Python — we need an async event loop.

import argparse
# For parsing command-line arguments like --compact and --single.

import sys
# For sys.exit() on errors.

from agent import NLPAgent, QuestionGenerationRequest
# Import the agent and its request contract directly.
# No HTTP, no server — we're calling the agent's Python methods.


# ---------------------------------------------------------------------------
# Candidate CV for testing
# ---------------------------------------------------------------------------

TEST_CV = """Candidate: Oussema Aissaoui
Role applied for: AI Engineering Intern

Education:
- National School of Computer Science (ENSI), Computer Engineering, Sep 2023–Present
  Coursework: AI, Data Analysis, Machine Learning, Software Engineering

Experience:
- Technology Intern, TALAN Tunisia, Jul–Aug 2025
  Applied GraphRAG and LLM reasoning for pattern recognition in enterprise datasets.
  Designed AI-driven prototypes for data analytics and business decision systems.
- AI & Automation Intern, NP Tunisia, Jul–Aug 2024
  Automated integration of 30+ industrial screens into a local network.

Projects:
- Pattern Recognition in Company Internal Data: GraphRAG + LLM reasoning on enterprise datasets.
- Blood Cell Segmentation: YOLOv8 + SAM pipeline for WBC/RBC classification and anomaly detection.
- Water Use Efficiency Estimation: ML model using WaPOR + Google Earth Engine for crop evapotranspiration.
- Blockchain E-Commerce: Decentralized marketplace using Solidity smart contracts.

Technical Skills:
- Languages: Python, C/C++, Java, JavaScript, Solidity
- AI & Data: ML, Deep Learning, TensorFlow, OpenCV, YOLOv8, SAM, NLP, GraphRAG
"""
# Hardcoded CV for testing. In production, this comes from the orchestrator.


# ---------------------------------------------------------------------------
# Interactive chat test
# ---------------------------------------------------------------------------

async def run_chat(agent: NLPAgent):
    """
    Run an interactive chat session with the agent.

    You type as the candidate, the agent responds as the recruiter.
    This simulates the full interview flow without any server.
    """

    session_id = "test-session-001"
    # Arbitrary session ID. In production, this is generated by the orchestrator.

    job_role = "AI Engineering Intern"
    # The job role shapes the interview focus.

    history: list[tuple[str, str]] = []
    # Conversation history: [(candidate_answer, recruiter_question), ...]
    # Starts empty — the first turn is the opening greeting.

    print("\n" + "=" * 70)
    print("🎤 NLP Agent — Direct Test Mode")
    print("=" * 70)
    print("You are the candidate. Type your answers.")
    print("Commands: /quit  /restart  /debug  /status")
    print("=" * 70 + "\n")

    while True:
        # --- Get candidate input ---
        try:
            candidate_input = input("Candidate > ").strip()
            # Read input from the terminal.
            # .strip() removes leading/trailing whitespace.
        except (EOFError, KeyboardInterrupt):
            # EOFError: input stream ended (piped input finished).
            # KeyboardInterrupt: user pressed Ctrl+C.
            print("\n\n✅ Interview ended.")
            break

        # --- Handle commands ---
        if not candidate_input:
            print("Please type something.\n")
            continue
            # Skip empty inputs.

        if candidate_input.lower() in {"/quit", "quit", "exit"}:
            print("\n✅ Interview ended. Good luck!")
            break

        if candidate_input.lower() == "/restart":
            agent.reset_session(session_id)
            # Reset the state tracker without destroying the session.
            history = []
            # Clear local history too.
            print("\n🔄 Interview reset. Starting fresh.\n")
            continue

        if candidate_input.lower() == "/debug":
            # Show detailed analysis of the PREVIOUS answer.
            if history:
                last_answer = history[-1][0]
                analysis = agent.analyze_response(session_id, last_answer)
                print(f"\n[DEBUG] Last answer analysis:")
                for key, value in analysis.items():
                    print(f"  {key}: {value}")
                print()
            else:
                print("\n[DEBUG] No previous answer to analyze.\n")
            continue

        if candidate_input.lower() == "/status":
            stats = agent.get_session_stats(session_id)
            print(f"\n[STATUS]")
            for key, value in stats.items():
                print(f"  {key}: {value}")
            print()
            continue

        # --- Build the request ---
        request = QuestionGenerationRequest(
            candidate_cv=TEST_CV,
            # The candidate's CV — used to build the system prompt.

            job_role=job_role,
            # Job title for interview focus.

            conversation_history=history[-6:],
            # Last 6 turns of history.
            # [-6:] = slice the last 6 elements (or all if fewer than 6).

            candidate_latest_answer=candidate_input,
            # What the candidate just said.

            session_id=session_id,
            # The session ID for state tracking.
        )

        # --- Generate the recruiter's question ---
        try:
            response = await agent.generate_question(request)
            # This is the main call. It:
            # 1. Analyzes the answer
            # 2. Decides follow-up vs new topic
            # 3. Runs vLLM inference
            # 4. Validates and cleans the response
        except Exception as e:
            print(f"\n❌ Generation error: {e}\n")
            continue

        # --- Display the response ---
        print(f"\nRecruiter > {response.question}")
        # The actual question to display/speak.

        # Status indicator
        if response.is_follow_up:
            indicator = "🔄 FOLLOW-UP"
        else:
            indicator = "➡️  NEW TOPIC"
        # Visual indicator showing whether we're digging deeper or moving on.

        # Metrics
        ttft_str = f"{response.metrics.ttft_sec:.2f}s" if response.metrics.ttft_sec else "N/A"
        # Format TTFT. Show "N/A" if no tokens were generated.

        print(
            f"[{indicator} | "
            f"reason={response.reasoning} | "
            f"depth={response.topic_depth} | "
            f"turn={response.turn_count} | "
            f"ttft={ttft_str} | "
            f"latency={response.metrics.latency_sec:.2f}s | "
            f"tokens={response.metrics.num_tokens} | "
            f"tok/s={response.metrics.tokens_per_sec:.1f}]"
        )
        print()

        # --- Update history ---
        history.append((candidate_input, response.question))
        # Add this turn to the conversation history.
        # Next time, the model will see this in its context.

    # --- Cleanup ---
    agent.end_session(session_id)
    # Release session resources.


# ---------------------------------------------------------------------------
# Single-shot test
# ---------------------------------------------------------------------------

async def run_single(agent: NLPAgent, candidate_answer: str):
    """
    Generate a single response — useful for quick testing.

    Args:
        agent: The NLP agent.
        candidate_answer: A single candidate answer to respond to.
    """

    session_id = "test-single"

    request = QuestionGenerationRequest(
        candidate_cv=TEST_CV,
        job_role="AI Engineering Intern",
        conversation_history=[],
        # No history for single-shot mode.
        candidate_latest_answer=candidate_answer,
        session_id=session_id,
    )

    print(f"\n{'='*70}")
    print(f"CANDIDATE : {candidate_answer}")
    print(f"{'='*70}")

    response = await agent.generate_question(request)
    # Generate one question.

    print(f"RECRUITER : {response.question}")
    print(f"REASONING : {response.reasoning}")
    print(f"FOLLOW-UP : {response.is_follow_up}")
    print(f"TTFT      : {response.metrics.ttft_sec:.3f}s" if response.metrics.ttft_sec else "TTFT      : N/A")
    print(f"LATENCY   : {response.metrics.latency_sec:.3f}s")
    print(f"TOKENS    : {response.metrics.num_tokens}")
    print(f"TOK/SEC   : {response.metrics.tokens_per_sec:.1f}")
    print(f"{'='*70}\n")

    agent.end_session(session_id)


# ---------------------------------------------------------------------------
# Batch test (multiple scenarios)
# ---------------------------------------------------------------------------

async def run_batch(agent: NLPAgent):
    """
    Run a batch of test scenarios to verify agent behavior.

    Tests various answer types:
    - Opening (first turn)
    - Very short answer
    - Detailed answer
    - Skip request
    - Nonsense answer
    """

    session_id = "test-batch"
    job_role = "AI Engineering Intern"
    history: list[tuple[str, str]] = []

    test_scenarios = [
        ("hello im ready for the interview", "Opening turn — should greet"),
        ("I worked on GraphRAG", "Very short — should follow up"),
        ("yes", "Extremely short — should follow up again"),
        (
            "I built a knowledge graph from enterprise documents using Neo4j, "
            "then applied LLM reasoning with a fine-tuned model to detect "
            "anomalous patterns in transaction data. We achieved 94% precision "
            "on the validation set and reduced false positives by 40%.",
            "Detailed — should move to new topic"
        ),
        ("can we skip this topic", "Skip request — should respect it"),
        ("haha idk", "Nonsense — should redirect gently"),
    ]
    # Each scenario is (candidate_answer, expected_behavior_description).

    print(f"\n{'='*70}")
    print(f"🧪 Batch Test — {len(test_scenarios)} scenarios")
    print(f"{'='*70}\n")

    for i, (answer, description) in enumerate(test_scenarios, 1):
        # enumerate(list, 1) starts counting from 1.

        print(f"--- Scenario {i}/{len(test_scenarios)}: {description} ---")
        print(f"CANDIDATE: {answer[:80]}{'...' if len(answer) > 80 else ''}")
        # Truncate long answers for display.

        request = QuestionGenerationRequest(
            candidate_cv=TEST_CV,
            job_role=job_role,
            conversation_history=history[-6:],
            candidate_latest_answer=answer,
            session_id=session_id,
        )

        response = await agent.generate_question(request)

        indicator = "🔄 FOLLOW-UP" if response.is_follow_up else "➡️  NEW TOPIC"
        print(f"RECRUITER: {response.question}")
        print(f"STATUS:    {indicator} | reason={response.reasoning}")
        print(f"METRICS:   ttft={response.metrics.ttft_sec:.2f}s | latency={response.metrics.latency_sec:.2f}s" if response.metrics.ttft_sec else f"METRICS:   latency={response.metrics.latency_sec:.2f}s")
        print()

        history.append((answer, response.question))
        # Accumulate history so later scenarios see previous turns.

    agent.end_session(session_id)
    print(f"{'='*70}")
    print(f"✅ Batch test complete")
    print(f"{'='*70}\n")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="NLP Agent Direct Test")

    parser.add_argument(
        "--single",
        type=str,
        default=None,
        help="Single-shot mode: provide one candidate answer",
    )
    # Example: python test_agent.py --single "I used Python for ML"

    parser.add_argument(
        "--batch",
        action="store_true",
        help="Run batch test scenarios",
    )
    # Example: python test_agent.py --batch

    parser.add_argument(
        "--compact",
        action="store_true",
        help="Use compact system prompt (faster TTFT)",
    )
    # Example: python test_agent.py --compact

    parser.add_argument(
        "--max-model-len",
        type=int,
        default=2048,
        help="Max context length for vLLM (default: 2048)",
    )

    parser.add_argument(
        "--gpu-memory",
        type=float,
        default=0.92,
        help="GPU memory fraction (default: 0.92)",
    )

    args = parser.parse_args()
    # Parse command-line arguments.

    print("\n🔧 Initializing NLP Agent...")
    print("   (This loads the model — takes ~60 seconds)\n")

    # --- Create the agent ---
    agent = NLPAgent(
        use_compact_prompt=args.compact,
        max_model_len=args.max_model_len,
        gpu_memory_utilization=args.gpu_memory,
    )
    # This loads the model into GPU memory.
    # The model_path default is set inside NLPAgent.__init__().

    async def _run():
        """Async wrapper for the test functions."""

        print("🔥 Warming up engine...\n")
        await agent.warmup()
        # Prime KV cache and CUDA graphs.

        if args.single:
            await run_single(agent, args.single)
        elif args.batch:
            await run_batch(agent)
        else:
            await run_chat(agent)
            # Default: interactive chat mode.

    asyncio.run(_run())
    # asyncio.run() creates an event loop and runs the async function.
    # This is the standard way to run async code from synchronous Python.


if __name__ == "__main__":
    main()
    # Only run if this file is executed directly (not imported).